version: 1.0.1.{build}
image: Previous Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: false
  verbosity: minimal
deploy:
- provider: Environment
  name: BitPantry NuGet
  on:
    branch: master